---
services:
- type: web
  name: gitpod-openvscode-server-example
  runtime: image
  image:
    url: gitpod/openvscode-server
  disk:
    name: data
    mountPath: "/home/workspace"
    sizeGB: 1
  envVars:
  - key: PORT
    value: 3000
