services:
- type: web
  name: gitpod-openvscode-server-example
  env: docker
  image:
    url: gitpod/openvscode-server
  autoDeploy: false
  envVars: # Environment variables
  - key: PORT
    value: 3000
  disk:
    name: data
    mountPath: /home/workspace
    sizeGB: 1
